# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Layout/ChangePurchasedService.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ChangePurchasedService(object):
    def setupUi(self, ChangePurchasedService):
        ChangePurchasedService.setObjectName("ChangePurchasedService")
        ChangePurchasedService.resize(400, 316)
        ChangePurchasedService.setStyleSheet("font: 13pt \"MS Shell Dlg 2\";")
        self.formLayoutWidget = QtWidgets.QWidget(ChangePurchasedService)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 10, 379, 290))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(10, 10, 10, 10)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.label_5 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.label_6 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.StartTime = QtWidgets.QDateTimeEdit(self.formLayoutWidget)
        self.StartTime.setObjectName("StartTime")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.StartTime)
        self.EndTime = QtWidgets.QDateTimeEdit(self.formLayoutWidget)
        self.EndTime.setObjectName("EndTime")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.EndTime)
        self.Visitor_ID = QtWidgets.QComboBox(self.formLayoutWidget)
        self.Visitor_ID.setObjectName("Visitor_ID")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.Visitor_ID)
        self.Staff_ID = QtWidgets.QComboBox(self.formLayoutWidget)
        self.Staff_ID.setObjectName("Staff_ID")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.Staff_ID)
        self.Services_ID = QtWidgets.QComboBox(self.formLayoutWidget)
        self.Services_ID.setObjectName("Services_ID")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.Services_ID)
        self.pushButton = QtWidgets.QPushButton(self.formLayoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.SpanningRole, self.pushButton)
        self.Price = QtWidgets.QDoubleSpinBox(self.formLayoutWidget)
        self.Price.setObjectName("Price")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.Price)

        self.retranslateUi(ChangePurchasedService)
        QtCore.QMetaObject.connectSlotsByName(ChangePurchasedService)

    def retranslateUi(self, ChangePurchasedService):
        _translate = QtCore.QCoreApplication.translate
        ChangePurchasedService.setWindowTitle(_translate("ChangePurchasedService", "Добавить/Изменить услуги"))
        self.label.setText(_translate("ChangePurchasedService", "ID посетителя"))
        self.label_2.setText(_translate("ChangePurchasedService", "ID сотрудника"))
        self.label_3.setText(_translate("ChangePurchasedService", "ID услуги"))
        self.label_4.setText(_translate("ChangePurchasedService", "Цена"))
        self.label_5.setText(_translate("ChangePurchasedService", "Время начала"))
        self.label_6.setText(_translate("ChangePurchasedService", "Время конца"))
        self.pushButton.setText(_translate("ChangePurchasedService", "ОК"))
