# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Layout/LoginWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoginWindow(object):
    def setupUi(self, LoginWindow):
        LoginWindow.setObjectName("LoginWindow")
        LoginWindow.resize(340, 300)
        self.pushLogin = QtWidgets.QPushButton(LoginWindow)
        self.pushLogin.setGeometry(QtCore.QRect(130, 220, 93, 28))
        self.pushLogin.setObjectName("pushLogin")
        self.Login = QtWidgets.QLineEdit(LoginWindow)
        self.Login.setGeometry(QtCore.QRect(70, 60, 200, 30))
        self.Login.setObjectName("Login")
        self.lineEdit_2 = QtWidgets.QLineEdit(LoginWindow)
        self.lineEdit_2.setGeometry(QtCore.QRect(90, 160, 200, 30))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label = QtWidgets.QLabel(LoginWindow)
        self.label.setGeometry(QtCore.QRect(120, 30, 55, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(LoginWindow)
        self.label_2.setGeometry(QtCore.QRect(120, 110, 55, 16))
        self.label_2.setObjectName("label_2")
        self.pushReg = QtWidgets.QPushButton(LoginWindow)
        self.pushReg.setGeometry(QtCore.QRect(230, 120, 93, 28))
        self.pushReg.setObjectName("pushReg")

        self.retranslateUi(LoginWindow)
        QtCore.QMetaObject.connectSlotsByName(LoginWindow)

    def retranslateUi(self, LoginWindow):
        _translate = QtCore.QCoreApplication.translate
        LoginWindow.setWindowTitle(_translate("LoginWindow", "Form"))
        self.pushLogin.setText(_translate("LoginWindow", "Войти"))
        self.label.setText(_translate("LoginWindow", "TextLabel"))
        self.label_2.setText(_translate("LoginWindow", "TextLabel"))
        self.pushReg.setText(_translate("LoginWindow", "Регистрация"))
