# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Layout/RegWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RegWindow(object):
    def setupUi(self, RegWindow):
        RegWindow.setObjectName("RegWindow")
        RegWindow.resize(400, 300)
        self.pushButton = QtWidgets.QPushButton(RegWindow)
        self.pushButton.setGeometry(QtCore.QRect(90, 240, 93, 28))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(RegWindow)
        QtCore.QMetaObject.connectSlotsByName(RegWindow)

    def retranslateUi(self, RegWindow):
        _translate = QtCore.QCoreApplication.translate
        RegWindow.setWindowTitle(_translate("RegWindow", "Form"))
        self.pushButton.setText(_translate("RegWindow", "PushButton"))
