# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Layout/RegWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RegWindow(object):
    def setupUi(self, RegWindow):
        RegWindow.setObjectName("RegWindow")
        RegWindow.setEnabled(True)
        RegWindow.resize(260, 300)
        self.pushButton = QtWidgets.QPushButton(RegWindow)
        self.pushButton.setGeometry(QtCore.QRect(50, 260, 151, 28))
        self.pushButton.setObjectName("pushButton")
        self.Surname = QtWidgets.QLineEdit(RegWindow)
        self.Surname.setGeometry(QtCore.QRect(100, 60, 141, 30))
        self.Surname.setObjectName("Surname")
        self.Name = QtWidgets.QLineEdit(RegWindow)
        self.Name.setGeometry(QtCore.QRect(100, 100, 141, 30))
        self.Name.setObjectName("Name")
        self.PhoneNumber = QtWidgets.QLineEdit(RegWindow)
        self.PhoneNumber.setGeometry(QtCore.QRect(100, 170, 141, 30))
        self.PhoneNumber.setObjectName("PhoneNumber")
        self.labelReg = QtWidgets.QLabel(RegWindow)
        self.labelReg.setGeometry(QtCore.QRect(20, 20, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.labelReg.setFont(font)
        self.labelReg.setObjectName("labelReg")
        self.Email = QtWidgets.QLineEdit(RegWindow)
        self.Email.setGeometry(QtCore.QRect(100, 210, 141, 30))
        self.Email.setObjectName("Email")
        self.label_2 = QtWidgets.QLabel(RegWindow)
        self.label_2.setGeometry(QtCore.QRect(0, 60, 91, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(RegWindow)
        self.label_3.setGeometry(QtCore.QRect(0, 100, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(RegWindow)
        self.label_4.setGeometry(QtCore.QRect(0, 170, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(RegWindow)
        self.label_5.setGeometry(QtCore.QRect(0, 210, 91, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.pushButton_2 = QtWidgets.QPushButton(RegWindow)
        self.pushButton_2.setGeometry(QtCore.QRect(200, 22, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.line = QtWidgets.QFrame(RegWindow)
        self.line.setGeometry(QtCore.QRect(20, 140, 221, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")

        self.retranslateUi(RegWindow)
        QtCore.QMetaObject.connectSlotsByName(RegWindow)

    def retranslateUi(self, RegWindow):
        _translate = QtCore.QCoreApplication.translate
        RegWindow.setWindowTitle(_translate("RegWindow", "Регистрация"))
        self.pushButton.setText(_translate("RegWindow", "Зарегистрироваться"))
        self.labelReg.setText(_translate("RegWindow", "Регистрация"))
        self.label_2.setText(_translate("RegWindow", "Фамилия:"))
        self.label_3.setText(_translate("RegWindow", "Имя:"))
        self.label_4.setText(_translate("RegWindow", "Телефон:"))
        self.label_5.setText(_translate("RegWindow", "Email:"))
        self.pushButton_2.setText(_translate("RegWindow", "Вход"))
