# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Layout/StaffWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_StaffWindow(object):
    def setupUi(self, StaffWindow):
        StaffWindow.setObjectName("StaffWindow")
        StaffWindow.resize(525, 325)
        self.centralwidget = QtWidgets.QWidget(StaffWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushExit = QtWidgets.QPushButton(self.centralwidget)
        self.pushExit.setGeometry(QtCore.QRect(380, 0, 141, 31))
        self.pushExit.setObjectName("pushExit")
        self.treeWidget = QtWidgets.QTreeWidget(self.centralwidget)
        self.treeWidget.setGeometry(QtCore.QRect(0, 30, 521, 291))
        self.treeWidget.setObjectName("treeWidget")
        StaffWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(StaffWindow)
        QtCore.QMetaObject.connectSlotsByName(StaffWindow)

    def retranslateUi(self, StaffWindow):
        _translate = QtCore.QCoreApplication.translate
        StaffWindow.setWindowTitle(_translate("StaffWindow", "MainWindow"))
        self.pushExit.setText(_translate("StaffWindow", "Выход"))
        self.treeWidget.headerItem().setText(0, _translate("StaffWindow", "Время начала"))
        self.treeWidget.headerItem().setText(1, _translate("StaffWindow", "Время конца"))
        self.treeWidget.headerItem().setText(2, _translate("StaffWindow", "Фамилия заказчика"))
        self.treeWidget.headerItem().setText(3, _translate("StaffWindow", "Имя заказчика"))
        self.treeWidget.headerItem().setText(4, _translate("StaffWindow", "Кем он работает"))
