# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Layout/YieldWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_YieldWindow(object):
    def setupUi(self, YieldWindow):
        YieldWindow.setObjectName("YieldWindow")
        YieldWindow.resize(434, 332)
        self.centralwidget = QtWidgets.QWidget(YieldWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.formLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(0, 0, 431, 381))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.formLayoutWidget.sizePolicy().hasHeightForWidth())
        self.formLayoutWidget.setSizePolicy(sizePolicy)
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(10, 10, 10, 10)
        self.formLayout.setObjectName("formLayout")
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.startTime = QtWidgets.QDateTimeEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.startTime.setFont(font)
        self.startTime.setObjectName("startTime")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.startTime)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.endTime = QtWidgets.QDateTimeEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.endTime.setFont(font)
        self.endTime.setObjectName("endTime")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.endTime)
        self.tableWidget = QtWidgets.QTableWidget(self.formLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.SpanningRole, self.tableWidget)
        self.findButton = QtWidgets.QPushButton(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.findButton.setFont(font)
        self.findButton.setObjectName("findButton")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.SpanningRole, self.findButton)
        YieldWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(YieldWindow)
        QtCore.QMetaObject.connectSlotsByName(YieldWindow)

    def retranslateUi(self, YieldWindow):
        _translate = QtCore.QCoreApplication.translate
        YieldWindow.setWindowTitle(_translate("YieldWindow", "Доходность"))
        self.label_2.setText(_translate("YieldWindow", "Время начала:"))
        self.label_3.setText(_translate("YieldWindow", "Время конца:"))
        self.findButton.setText(_translate("YieldWindow", "Найти"))
